### ISSUE TITLE
images with odd width generate incorrect output

### ISSUE THREAD

**Issue by fireattack** [catdad-experiments/heic-cli#6]
Image is from an iPhone from a friend (didn't know the spec).

https://www.dropbox.com/s/l36ivq71ejpsmdo/IMG_6744.HEIC?dl=0

The correct result should be something like

![image](https://user-images.githubusercontent.com/4130991/94364296-d2aeec80-008d-11eb-9a61-07bd83dd93c5.png)

heic-cli outputs:

![image](https://user-images.githubusercontent.com/4130991/94364302-de021800-008d-11eb-88ec-2ca4cac35bd4.png)

**Comment by catdad** [comment]
This is caused by an issue in `libheif`. Specifically: https://github.com/strukturag/libheif/issues/335

Since that issue is already assigned, I'll wait a little bit to see if it gets any momentum.

To clarify, this issue happens with images that have a width that is odd -- in the case of the image above, it was cropped to a width of 3937.

**Comment by catdad** [comment]
This was technically already addressed a while ago within dependencies of this lib that would have been installed automatically, but I also just released 1.1.1 to make those new dependencies the required minimum version.
